# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: THEOplayer Open Video UI for Web
description: >- # this means to ignore newlines until "baseurl:"
  UI component library for the THEOplayer Web SDK
baseurl: /web-ui # the subpath of your site, e.g. /blog
url: https://theoplayer.github.io # the base hostname & protocol for your site, e.g. http://example.com
author: THEO Technologies
github_username: THEOplayer
github_url: https://github.com/THEOplayer/web-ui
theoplayer_license: sZP7IYe6T6Pe3LP63uRr3Zk63oP1FSaz3Sa-CK0rC6zk3S0c0Lg13lhc0l56FOPlUY3zWokgbgjNIOf9fKBz3LBo3DaoFSeZ0Se-3uetIOk60QCZFDao0LA63QXlCL0i0OfVfK4_bQgZCYxNWoryIQXzImf90SbLTu0c3LCi0u5i0Oi6Io4pIYP1UQgqWgjeCYxgflEc3lRi3SerTSai0u0iFOPeWok1dDrLYtA1Ioh6TgV6WQjlCDcEWt3zf6i6UQ1gWtAVCYggb6rlWoz6FOPzdQ4qbQc1sD4ZFKUNUQ1kC6rNWZPUFOPeWok1dDrLYt3qUYPlImf9DZfJf6i6WQjlCDcEWt3zf6i6UQ1gWtAVCYggb6rlWoz6Ymi6box7bZf9DZPEUQkV3mPUFOPLIDreYog-bwPgbt3NWo_6TGxZUDhVfKIgCYxkbK4LflNWYYz

# Build settings
theme: minima
plugins:
  - jekyll-copyr

jekyll-copyr:
  enabled: true
  tasks:
    - from: '../dist/.'
      to: './_site/dist/'
    - from: '../react/dist/.'
      to: './_site/dist/'
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
